language: python
python:
  - "3.5.2"
  - "2.7.12"
services:
- postgresql

before_script:
- psql -c 'CREATE DATABASE testdb;' -U postgres
- psql -c "CREATE USER test123 WITH PASSWORD 'test123';" -U postgres
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=api/
  - coveralls
after_success:
 # - coveralls
